export enum EmailTemplate {
  OTP_VERIFY = 'otpVerify',
  OTP_RESEND = 'otpResend',
  PASSWORD_RESET = 'passwordReset',
  PASSWORD_CHANGED = 'passwordChanged',
  TUTOR_CREATED = 'tutorCreated',
  ADMIN_CREATED = 'adminCreated',
  LOGIN_ALERT = 'loginAlert',
  PROFILE_UPDATED = 'profileUpdated',
  SOCIAL_WELCOME = 'socialWelcome',
  EMAIL_VERIFIED = 'emailVerified',
  CERTIFICATE_ISSUED = 'certificateIssued',
  QUIZ_SCORE_HIGH = 'quizScoreHigh',
  QUIZ_SCORE_AVERAGE = 'quizScoreAverage',
  QUIZ_SCORE_LOW = 'quizScoreLow',
  ASSIGNMENT_GRADED = 'assignmentGraded',
  COURSE_ANNOUNCEMENT = 'courseAnnouncement',
  COURSE_EVENT = 'courseEvent',
  NOTIFICATION_DETAILED = 'notificationDetailed',
  SUBSCRIPTION_UPDATED = 'subscriptionUpdated',
  ACCOUNT_SUSPENDED = 'accountSuspended',
  ACCOUNT_REACTIVATED = 'accountReactivated',
  ACCOUNT_DEACTIVATED = 'accountDeactivated',
  ROLE_CHANGED = 'roleChanged',
}
